const imagesActionTypes = {
  FETCH_IMAGES_REQUESTED: 'FETCH_IMAGES_REQUESTED',
  FETCH_IMAGES_SUCCEEDED: 'FETCH_IMAGES_SUCCEEDED',
  FETCH_IMAGES_FAILED: 'FETCH_IMAGES_FAILED',
};

export default imagesActionTypes;
